name: water_animation
description: "Water Animation is a Flutter widget for customizable water effects with animated waves, gradient fills, and ripple effects."
version: 0.0.2
homepage: "https://github.com/mustafakilic097/water_animation.git"
repository: "https://github.com/mustafakilic097/water_animation.git"

environment:
  sdk: ^3.7.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true